name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ https://gist.github.com/qlstn9150/ }}
          TIMEZONE: Asia/Seoul
